	TEDv3_architecture u0 (
		.black_interface_mac_mdio_connection_mdc           (<connected-to-black_interface_mac_mdio_connection_mdc>),           //         black_interface_mac_mdio_connection.mdc
		.black_interface_mac_mdio_connection_mdio_in       (<connected-to-black_interface_mac_mdio_connection_mdio_in>),       //                                            .mdio_in
		.black_interface_mac_mdio_connection_mdio_out      (<connected-to-black_interface_mac_mdio_connection_mdio_out>),      //                                            .mdio_out
		.black_interface_mac_mdio_connection_mdio_oen      (<connected-to-black_interface_mac_mdio_connection_mdio_oen>),      //                                            .mdio_oen
		.black_interface_mac_misc_connection_xon_gen       (<connected-to-black_interface_mac_misc_connection_xon_gen>),       //         black_interface_mac_misc_connection.xon_gen
		.black_interface_mac_misc_connection_xoff_gen      (<connected-to-black_interface_mac_misc_connection_xoff_gen>),      //                                            .xoff_gen
		.black_interface_mac_misc_connection_ff_tx_crc_fwd (<connected-to-black_interface_mac_misc_connection_ff_tx_crc_fwd>), //                                            .ff_tx_crc_fwd
		.black_interface_mac_misc_connection_ff_tx_septy   (<connected-to-black_interface_mac_misc_connection_ff_tx_septy>),   //                                            .ff_tx_septy
		.black_interface_mac_misc_connection_tx_ff_uflow   (<connected-to-black_interface_mac_misc_connection_tx_ff_uflow>),   //                                            .tx_ff_uflow
		.black_interface_mac_misc_connection_ff_tx_a_full  (<connected-to-black_interface_mac_misc_connection_ff_tx_a_full>),  //                                            .ff_tx_a_full
		.black_interface_mac_misc_connection_ff_tx_a_empty (<connected-to-black_interface_mac_misc_connection_ff_tx_a_empty>), //                                            .ff_tx_a_empty
		.black_interface_mac_misc_connection_rx_err_stat   (<connected-to-black_interface_mac_misc_connection_rx_err_stat>),   //                                            .rx_err_stat
		.black_interface_mac_misc_connection_rx_frm_type   (<connected-to-black_interface_mac_misc_connection_rx_frm_type>),   //                                            .rx_frm_type
		.black_interface_mac_misc_connection_ff_rx_dsav    (<connected-to-black_interface_mac_misc_connection_ff_rx_dsav>),    //                                            .ff_rx_dsav
		.black_interface_mac_misc_connection_ff_rx_a_full  (<connected-to-black_interface_mac_misc_connection_ff_rx_a_full>),  //                                            .ff_rx_a_full
		.black_interface_mac_misc_connection_ff_rx_a_empty (<connected-to-black_interface_mac_misc_connection_ff_rx_a_empty>), //                                            .ff_rx_a_empty
		.black_interface_mac_rgmii_connection_rgmii_in     (<connected-to-black_interface_mac_rgmii_connection_rgmii_in>),     //        black_interface_mac_rgmii_connection.rgmii_in
		.black_interface_mac_rgmii_connection_rgmii_out    (<connected-to-black_interface_mac_rgmii_connection_rgmii_out>),    //                                            .rgmii_out
		.black_interface_mac_rgmii_connection_rx_control   (<connected-to-black_interface_mac_rgmii_connection_rx_control>),   //                                            .rx_control
		.black_interface_mac_rgmii_connection_tx_control   (<connected-to-black_interface_mac_rgmii_connection_tx_control>),   //                                            .tx_control
		.black_interface_mac_status_connection_set_10      (<connected-to-black_interface_mac_status_connection_set_10>),      //       black_interface_mac_status_connection.set_10
		.black_interface_mac_status_connection_set_1000    (<connected-to-black_interface_mac_status_connection_set_1000>),    //                                            .set_1000
		.black_interface_mac_status_connection_eth_mode    (<connected-to-black_interface_mac_status_connection_eth_mode>),    //                                            .eth_mode
		.black_interface_mac_status_connection_ena_10      (<connected-to-black_interface_mac_status_connection_ena_10>),      //                                            .ena_10
		.black_interface_pcs_mac_rx_clock_connection_clk   (<connected-to-black_interface_pcs_mac_rx_clock_connection_clk>),   // black_interface_pcs_mac_rx_clock_connection.clk
		.black_interface_pcs_mac_tx_clock_connection_clk   (<connected-to-black_interface_pcs_mac_tx_clock_connection_clk>),   // black_interface_pcs_mac_tx_clock_connection.clk
		.clk_clk                                           (<connected-to-clk_clk>),                                           //                                         clk.clk
		.hex_conduit_hex_conduit                           (<connected-to-hex_conduit_hex_conduit>),                           //                                 hex_conduit.hex_conduit
		.input_port_external_connection_export             (<connected-to-input_port_external_connection_export>),             //              input_port_external_connection.export
		.lcd_clk_areset_conduit_export                     (<connected-to-lcd_clk_areset_conduit_export>),                     //                      lcd_clk_areset_conduit.export
		.lcd_clk_locked_conduit_export                     (<connected-to-lcd_clk_locked_conduit_export>),                     //                      lcd_clk_locked_conduit.export
		.lcd_clk_phasedone_conduit_export                  (<connected-to-lcd_clk_phasedone_conduit_export>),                  //                   lcd_clk_phasedone_conduit.export
		.lcd_external_interface_DATA                       (<connected-to-lcd_external_interface_DATA>),                       //                      lcd_external_interface.DATA
		.lcd_external_interface_ON                         (<connected-to-lcd_external_interface_ON>),                         //                                            .ON
		.lcd_external_interface_BLON                       (<connected-to-lcd_external_interface_BLON>),                       //                                            .BLON
		.lcd_external_interface_EN                         (<connected-to-lcd_external_interface_EN>),                         //                                            .EN
		.lcd_external_interface_RS                         (<connected-to-lcd_external_interface_RS>),                         //                                            .RS
		.lcd_external_interface_RW                         (<connected-to-lcd_external_interface_RW>),                         //                                            .RW
		.output_port_external_connection_export            (<connected-to-output_port_external_connection_export>),            //             output_port_external_connection.export
		.red_interface_mac_mdio_connection_mdc             (<connected-to-red_interface_mac_mdio_connection_mdc>),             //           red_interface_mac_mdio_connection.mdc
		.red_interface_mac_mdio_connection_mdio_in         (<connected-to-red_interface_mac_mdio_connection_mdio_in>),         //                                            .mdio_in
		.red_interface_mac_mdio_connection_mdio_out        (<connected-to-red_interface_mac_mdio_connection_mdio_out>),        //                                            .mdio_out
		.red_interface_mac_mdio_connection_mdio_oen        (<connected-to-red_interface_mac_mdio_connection_mdio_oen>),        //                                            .mdio_oen
		.red_interface_mac_misc_connection_xon_gen         (<connected-to-red_interface_mac_misc_connection_xon_gen>),         //           red_interface_mac_misc_connection.xon_gen
		.red_interface_mac_misc_connection_xoff_gen        (<connected-to-red_interface_mac_misc_connection_xoff_gen>),        //                                            .xoff_gen
		.red_interface_mac_misc_connection_ff_tx_crc_fwd   (<connected-to-red_interface_mac_misc_connection_ff_tx_crc_fwd>),   //                                            .ff_tx_crc_fwd
		.red_interface_mac_misc_connection_ff_tx_septy     (<connected-to-red_interface_mac_misc_connection_ff_tx_septy>),     //                                            .ff_tx_septy
		.red_interface_mac_misc_connection_tx_ff_uflow     (<connected-to-red_interface_mac_misc_connection_tx_ff_uflow>),     //                                            .tx_ff_uflow
		.red_interface_mac_misc_connection_ff_tx_a_full    (<connected-to-red_interface_mac_misc_connection_ff_tx_a_full>),    //                                            .ff_tx_a_full
		.red_interface_mac_misc_connection_ff_tx_a_empty   (<connected-to-red_interface_mac_misc_connection_ff_tx_a_empty>),   //                                            .ff_tx_a_empty
		.red_interface_mac_misc_connection_rx_err_stat     (<connected-to-red_interface_mac_misc_connection_rx_err_stat>),     //                                            .rx_err_stat
		.red_interface_mac_misc_connection_rx_frm_type     (<connected-to-red_interface_mac_misc_connection_rx_frm_type>),     //                                            .rx_frm_type
		.red_interface_mac_misc_connection_ff_rx_dsav      (<connected-to-red_interface_mac_misc_connection_ff_rx_dsav>),      //                                            .ff_rx_dsav
		.red_interface_mac_misc_connection_ff_rx_a_full    (<connected-to-red_interface_mac_misc_connection_ff_rx_a_full>),    //                                            .ff_rx_a_full
		.red_interface_mac_misc_connection_ff_rx_a_empty   (<connected-to-red_interface_mac_misc_connection_ff_rx_a_empty>),   //                                            .ff_rx_a_empty
		.red_interface_mac_rgmii_connection_rgmii_in       (<connected-to-red_interface_mac_rgmii_connection_rgmii_in>),       //          red_interface_mac_rgmii_connection.rgmii_in
		.red_interface_mac_rgmii_connection_rgmii_out      (<connected-to-red_interface_mac_rgmii_connection_rgmii_out>),      //                                            .rgmii_out
		.red_interface_mac_rgmii_connection_rx_control     (<connected-to-red_interface_mac_rgmii_connection_rx_control>),     //                                            .rx_control
		.red_interface_mac_rgmii_connection_tx_control     (<connected-to-red_interface_mac_rgmii_connection_tx_control>),     //                                            .tx_control
		.red_interface_mac_status_connection_set_10        (<connected-to-red_interface_mac_status_connection_set_10>),        //         red_interface_mac_status_connection.set_10
		.red_interface_mac_status_connection_set_1000      (<connected-to-red_interface_mac_status_connection_set_1000>),      //                                            .set_1000
		.red_interface_mac_status_connection_eth_mode      (<connected-to-red_interface_mac_status_connection_eth_mode>),      //                                            .eth_mode
		.red_interface_mac_status_connection_ena_10        (<connected-to-red_interface_mac_status_connection_ena_10>),        //                                            .ena_10
		.red_interface_pcs_mac_rx_clock_connection_clk     (<connected-to-red_interface_pcs_mac_rx_clock_connection_clk>),     //   red_interface_pcs_mac_rx_clock_connection.clk
		.red_interface_pcs_mac_tx_clock_connection_clk     (<connected-to-red_interface_pcs_mac_tx_clock_connection_clk>),     //   red_interface_pcs_mac_tx_clock_connection.clk
		.reset_reset_n                                     (<connected-to-reset_reset_n>)                                      //                                       reset.reset_n
	);

